FROM amazonlinux:latest
RUN amazon-linux-extras install python3
RUN pip3 install botocore
RUN pip3 install boto3
RUN yum -y update 
RUN yum -y install git
RUN yum -y install wget
RUN yum -y install tar
RUN yum -y install gzip
RUN yum -y install unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN git clone https://github.com/maheshda-aws/aws-beamline
RUN cd /aws-beamline && python3 setup.py bdist_wheel
RUN pip3 install --upgrade --force-reinstall  /aws-beamline/dist/awsbeamline-0.0.1-py3-none-any.whl
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
#ENV PATH=$PATH:/dsbulk/bin

