FROM amazonlinux:latest
RUN amazon-linux-extras install python3
RUN yum -y install git
RUN pip3 install --upgrade pip
RUN yum -y install unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN git clone https://github.com/maheshda-aws/aws-beamline
RUN cd /aws-beamline && python3 setup.py bdist_wheel
RUN pip3 install --upgrade --force-reinstall  /aws-beamline/dist/awsbeamline-0.0.1-py3-none-any.whl
RUN chmod +x  /aws-beamline/beamline.py
RUN mv  /aws-beamline/beamline.py /usr/bin/beamline
ENV PATH=$PATH:/usr/bin

